- job:
    name: promote-docs-base
    abstract: True
    run: playbooks/docs/promote.yaml
    nodeset:
      nodes: []

- job:
    name: promote-docs
    parent: promote-docs-base
    branches: build
    vars:
      download_artifact_job: tox-docs


- project:
    merge-mode: squash-merge
    check:
      jobs:
        - tox-docs
    gate:
      jobs:
        - tox-docs
    promote:
      jobs:
        - promote-docs
